name: Firmware CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PlatformIO
      uses: platformio/platformio-core-action@v1
      
    - name: Build Firmware
      run: |
        cd firmware
        pio run
        
    - name: Run Tests
      run: |
        pio test -e native
